version: '3'
services:
    express-typescript:
        build:
            context: .
            dockerfile: local.Dockerfile
        container_name: 'app-express-typescript'
        volumes:
            - .:/usr/src/app/
        working_dir: /usr/src/app
        command: sh -c "npm install && npm run start:dev"
        ports:
            - 3000:3000
    mongo:
        image: "mongo"
        ports:
        - "27017:27017"
        expose:
        - 27017
